### ISSUE TITLE
Could not find Gnome::Gtk3::Main

### ISSUE THREAD

**Issue by j-mckim** [MARTIMM/perl6-gnome-gtk3#17]
I'm working with raku as provided by the rakudo-moar-2020.12-01-linux-x86_64-gcc.tar.gz binary installation provided by radudo. Zef  (e.g. "zef install Gnome::Gtk3") proceeds up to the point where these diagnostics are issued:

===> Testing [OK] for Gnome::GObject:ver<0.16.16.2>
===> Testing: Gnome::Gio:ver<0.5.3>
[Gnome::Gio] ===SORRY!=== Error while compiling /home/jim/.zef/store/gnome-gio-0.5.3.tar.gz/gnome-gio-0.5.3/t/SimpleAction.t
[Gnome::Gio] Could not find Gnome::Gtk3::Main in:
[Gnome::Gio]     file#/home/jim/.zef/store/gnome-gio-0.5.3.tar.gz/gnome-gio-0.5.3
[Gnome::Gio]     file#/home/jim/.zef/store/gnome-native-0.18.7.1.tar.gz/gnome-native-0.18.7.1
[Gnome::Gio]     file#/home/jim/.zef/store/gnome-glib-0.18.2.tar.gz/gnome-glib-0.18.2
[Gnome::Gio]     file#/home/jim/.zef/store/gnome-gobject-0.16.16.2.tar.gz/gnome-gobject-0.16.16.2
[Gnome::Gio]     inst#/home/jim/.raku
[Gnome::Gio]     inst#/home/jim/rakudo-moar-2020.12-01-linux-x86_64-gcc/share/perl6/site
[Gnome::Gio]     inst#/home/jim/rakudo-moar-2020.12-01-linux-x86_64-gcc/share/perl6/vendor
[Gnome::Gio]     inst#/home/jim/rakudo-moar-2020.12-01-linux-x86_64-gcc/share/perl6/core
[Gnome::Gio]     ap#
[Gnome::Gio]     nqp#
[Gnome::Gio]     perl5#
[Gnome::Gio] Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Gnome::Gtk3::Main' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?
[Gnome::Gio] at /home/jim/.zef/store/gnome-gio-0.5.3.tar.gz/gnome-gio-0.5.3/t/SimpleAction.t:157
===> Testing [FAIL]: Gnome::Gio:ver<0.5.3>
Aborting due to test failure: Gnome::Gio:ver<0.5.3> (use --force-test to override)

Have you any suggestions? Raku reports its version as Rakudo v2020.12. Am I missing other prerequisites?

**Comment by MARTIMM** [comment]
Hi, 
I've just pushed Gnome::Gio:ver<0.5.3.1> to remedy this problem. I was using it there to test signals defined in a few modules of Gio. It was already mentioned [here Gnome::Gio #1](https://github.com/MARTIMM/gnome-gio/issues/1).
