### ISSUE TITLE
Returning True from delete-event signal doesn't leave window open

### ISSUE THREAD

**Issue by grenzionky** [MARTIMM/perl6-gnome-gtk3#22]
```
use Gnome::Gtk3::Main;
use Gnome::Gtk3::Window;

class Handlers {
	method on-close {
		say 'staying open';
		return True;
	}
}

my Gnome::Gtk3::Main $m .= new;
my Handlers $handler .= new;

given Gnome::Gtk3::Window.new {
  .set-size-request( 600, 300);
  .show-all;
  .register-signal($handler, 'on-close', 'delete-event');
}

$m.gtk-main;
```

The window here should stay open when the X button is pressed, but it doesn't...

It doesn't work when I return 1 either.

According to ↓ you should be able to cancel the delete event by returning True
- https://pygtk.daa.com.narkive.com/t6apmoiT/preventing-a-gtk-window-from-being-closed
- https://stackoverflow.com/questions/1037414/when-the-deleteevent-is-called-by-a-gtk-window-how-can-i-prevent-the-window-fr
- https://ubuntuforums.org/showthread.php?t=345313

Also, `delete-event` takes a GdkEvent argument that isn't accepted.

I'm not sure where you implemented this signal so idk where to go and make the necessary edits myself.

**Comment by MARTIMM** [comment]
A handler must be defined precisely, so if a return value is needed it must be described in the API.

I've seen that my documentation of Widget is not correct and needs to be improved. I already started with that module but it's about 8400 lines so it takes a while.
About the GdkEvent, It should indeed be there. Investigating the Widget module, I found a bug where the signal was wrongly categorized.

In the end, the method should be defined differently. Below is the complete program;
```
use Gnome::N::GlibToRakuTypes;
use Gnome::Gdk3::Events;
use Gnome::Gtk3::Main;
use Gnome::Gtk3::Window;

class Handlers {
	method on-close ( N-GdkEvent $event --> gboolean ) {
		say 'staying open: ', GdkEventType($event.event-any.type);
		1;
	}
}

my Gnome::Gtk3::Main $m .= new;
my Handlers $handler .= new;

given Gnome::Gtk3::Window.new {
  .set-size-request( 600, 300);
  .show-all;
  .register-signal($handler, 'on-close', 'delete-event');
}

$m.gtk-main;
```
The above code will now show `staying open: GDK_DELETE` and the window will stay open. This will work after pushing the next version of Gnome::Gtk3; 0.39.2.

I also have tried using the return type Int and Bool (returning True). Both work as well. but am not sure if there is some sort of caveat hidden there.

The module **Gnome::N::GlibToRakuTypes** is a mapping of many types used by glib to raku types. Some are convenient such as `gint`. This will map to `int32` or `int64` depending on your system. That module is generated on installation of `Gnome::N`.

**Comment by MARTIMM** [comment]
pushed Gnome::Gtk3; 0.39.2.

I've checked the types of a handler and you can use the Int and Bool types.

**Comment by grenzionky** [comment]
the update fails to build for me

```
[Gnome::Gtk3] ===SORRY!=== Error while compiling /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/t/menus.t
[Gnome::Gtk3] ===SORRY!=== Error while compiling /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/lib/Gnome/Gtk3/MenuBar.pm6 (Gnome::Gtk3::MenuBar)
[Gnome::Gtk3] ===SORRY!=== Error while compiling /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/home#sources/FD0D89B9EE60E6B56774ACF7F021A5B48D586689 (Gnome::N::NativeLib)
[Gnome::Gtk3] Redeclaration of routine 'gdk-lib'.  Did you mean to declare a
[Gnome::Gtk3] multi-sub?
[Gnome::Gtk3] at /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/home#sources/FD0D89B9EE60E6B56774ACF7F021A5B48D586689 (Gnome::N::NativeLib):13
[Gnome::Gtk3] ------>           is export { 'libgdk-3.so.0'; }⏏<EOL>
[Gnome::Gtk3] at /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/lib/Gnome/Gtk3/MenuBar.pm6 (Gnome::Gtk3::MenuBar):45
[Gnome::Gtk3] at /home/user/.zef/store/gnome-gtk3-0.39.2.tar.gz/gnome-gtk3-0.39.2/t/menus.t:8
===> Testing [FAIL]: Gnome::Gtk3:ver<0.39.2>
```

I'm pretty sure it does this for every class in Gtk3 and N and Gio and Gdk3

**Comment by MARTIMM** [comment]
This is a weird error. To test it, I have removed my gnome packages and reinstalled it again to see if I get the same errors. Although I do not get yours I see other problems. I will repair these and publish the new version.

**Comment by MARTIMM** [comment]
Pushed version Gnome::Gtk3 0.39.3. Also updated are Gnome::Glib 0.20.1 and less important Gnome::N 0.18.12.1.

Maybe it is important to uninstall the gnome installation before installing instead of updating.

**Comment by grenzionky** [comment]
I unistalled Gnome::* and then ran

```
~ > zef install Gnome::Gtk3
===> Searching for: Gnome::Gtk3
===> Searching for missing dependencies: Gnome::N, Gnome::Glib, Gnome::Gio, Gnome::Gdk3
===> Building: Gnome::N:ver<0.18.12.1>
===> Building [OK] for Gnome::N:ver<0.18.12.1>
===> Testing: Gnome::N:ver<0.18.12.1>
[Gnome::N]     # GEnum:        (int32)
[Gnome::N]     # GFlag:        (uint32)
[Gnome::N]     # GQuark:       (uint32)
[Gnome::N]     # GType:        (uint64)
[Gnome::N]     # char-ppptr:   (CArray[CArray[Str]])
[Gnome::N]     # char-pptr:    (CArray[Str])
[Gnome::N]     # gboolean:     (int32)
[Gnome::N]     # gchar:        (int8)
[Gnome::N]     # gchar-ppptr:  (CArray[CArray[Str]])
[Gnome::N]     # gchar-pptr:   (CArray[Str])
[Gnome::N]     # gchar-ptr:    (Str)
[Gnome::N]     # gdouble:      (num64)
[Gnome::N]     # gfloat:       (num32)
[Gnome::N]     # gint:         (int32)
[Gnome::N]     # gint-ptr:     (CArray[int32])
[Gnome::N]     # gint16:       (int16)
[Gnome::N]     # gint32:       (int32)
[Gnome::N]     # gint64:       (int64)
[Gnome::N]     # gint8:        (int8)
[Gnome::N]     # glong:        (int64)
[Gnome::N]     # gpointer:     (NativeCall::Types::Pointer)
[Gnome::N]     # gshort:       (int16)
[Gnome::N]     # gsize:        (uint64)
[Gnome::N]     # gssize:       (int64)
[Gnome::N]     # guchar:       (uint8)
[Gnome::N]     # guint:        (uint32)
[Gnome::N]     # guint16:      (uint16)
[Gnome::N]     # guint32:      (uint32)
[Gnome::N]     # guint64:      (uint64)
[Gnome::N]     # guint8:       (uint8)
[Gnome::N]     # gulong:       (uint64)
[Gnome::N]     # gushort:      (uint16)
[Gnome::N]     # int-ptr:      (CArray[int32])
[Gnome::N]     # time_t:       (int64)
[Gnome::N]     # void-ptr:     (NativeCall::Types::Pointer[NativeCall::Types::void])
[Gnome::N] ===SORRY!=== Error while compiling /home/user/.zef/store/gnome-native-0.18.12.1.tar.gz/gnome-native-0.18.12.1/t/NativeLib.t
[Gnome::N] ===SORRY!=== Error while compiling /home/user/.zef/store/gnome-native-0.18.12.1.tar.gz/gnome-native-0.18.12.1/lib/Gnome/N/NativeLib.pm6 (Gnome::N::NativeLib)
[Gnome::N] Redeclaration of routine 'gdk-lib'.  Did you mean to declare a
[Gnome::N] multi-sub?
[Gnome::N] at /home/user/.zef/store/gnome-native-0.18.12.1.tar.gz/gnome-native-0.18.12.1/lib/Gnome/N/NativeLib.pm6 (Gnome::N::NativeLib):13
[Gnome::N] ------>           is export { 'libgdk-3.so.0'; }⏏<EOL>
[Gnome::N] at /home/user/.zef/store/gnome-native-0.18.12.1.tar.gz/gnome-native-0.18.12.1/t/NativeLib.t:5
===> Testing [FAIL]: Gnome::N:ver<0.18.12.1>
Aborting due to test failure: Gnome::N:ver<0.18.12.1> (use --force-test to override)
```

and im still getting these errors

**Comment by MARTIMM** [comment]
The file where the error is is generated at build time. I would like you to show the file to see what is generated.(I believe the path on your system is; `/home/user/.zef/store/gnome-native-0.18.12.1.tar.gz/gnome-native-0.18.12.1/lib/Gnome/N/NativeLib.pm6`)
The build process is looking in your system using `ldconfig` for the installed libraries and then use the name in the generated file. Did you install something some short time ago? a compatibility version of some sort? You might also show me a list of `libgdk*` libs?

On my system
```
/usr/lib64/libgdk-1.2.so.0
/usr/lib64/libgdk-1.2.so.0.9.1
/usr/lib64/libgdk-3.so
/usr/lib64/libgdk-3.so.0
/usr/lib64/libgdk-3.so.0.2404.23
/usr/lib64/libgdk-x11-2.0.so.0
/usr/lib64/libgdk-x11-2.0.so.0.2400.32
/usr/lib64/libgdk_pixbuf-2.0.so
/usr/lib64/libgdk_pixbuf-2.0.so.0
/usr/lib64/libgdk_pixbuf-2.0.so.0.4000.0
```
or better, a list generated by `ldconfig -vN`

**Comment by grenzionky** [comment]
```
~ > sudo ldconfig -vN | grep -i gdk
ldconfig: Path `/usr/lib64' given more than once
(from <builtin>:0 and <builtin>:0)
ldconfig: Can't stat /usr/libx32: No such file or directory
	libgdk-x11-2.0.so.0 -> libgdk-x11-2.0.so.0.2400.33
	libgdk-3.so.0 -> libgdk-3.so.0.2404.23
	libgdk_pixbuf-2.0.so.0 -> libgdk_pixbuf-2.0.so.0.4200.6
	libgdk-3.so.0 -> libgdk-3.so.0.2404.25
	libgdksharpglue-2.so -> libgdksharpglue-2.so
	libgdk-x11-2.0.so.0 -> libgdk-x11-2.0.so.0.2400.33
	libgdkmm-2.4.so.1 -> libgdkmm-2.4.so.1.1.0
	libgdkmm-3.0.so.1 -> libgdkmm-3.0.so.1.1.0
	libgdk_pixbuf-2.0.so.0 -> libgdk_pixbuf-2.0.so.0.4200.6
	libgdk_pixbuf_xlib-2.0.so.0 -> libgdk_pixbuf_xlib-2.0.so.0.4000.2
```

**Comment by grenzionky** [comment]
so the problem was that i had 2 copies of libgdk and libgtk. one in /usr/lib32 and one in /usr/lib64. i removed the one from /usr/lib32 and now it works.

**Comment by MARTIMM** [comment]
Nice that you solved it. There might be situations that one needs a 32bit lib around. So, to prevent future problems I will check for double entries.

**Comment by MARTIMM** [comment]
pushed version Gnome::N 0.18.13
